### ISSUE TITLE
feat: add new content from V1.0.0 update

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#106]
Find all the new features shipped in the V1.0.0 update, and list them in this issue. We will need to update the related chapter sections to keep the book in date with the latest release.

- [x] remove gas checks in loops 
- [x] type casts:`uj` to `u_i` casting (except for u256) 
- [x] continue keyword in loops
- [x] united import like `use integer::{u16_sqrt, u32_sqrt, u64_sqrt, u8_sqrt, BoundedInt, u128_wrapping_sub};`
- [x] aliased imports like `use abc as def`
- [ ] store Dispatcher in storage access (not sure if should be included)
- [ ] interoperability testing in Starknet Contracts (mock caller / contract address, etc)
- [ ] Derives: Serde, [starknet::Event](https://github.com/starkware-libs/cairo/commit/c0fa81e9908bba08085786cd33165bcf3a9ace97#diff-f9fc8d72081d5425acd91ce848e3fbaedd5df3166afafabfaa501b23ea9f7ee4),  (can go in appendix)
- [ ] [impl aliases](https://github.com/starkware-libs/cairo/commit/7bbbc7d52ceeb471a5de31d8aa39e320e00d6a30#diff-f9fc8d72081d5425acd91ce848e3fbaedd5df3166afafabfaa501b23ea9f7ee4) (low priority)
- [x] Use type inference in code snippets
- [x] syntax change from  `#[should_panic(expected= ('assert(false)', ))]` to `#[should_panic(expected: ('assert(false)', ))]`
- [x] u256 literals: remove all primitive u256 casts that use `.into()`
- [x] type inference: remove type literals (change all`1_usize` to `1`)

Unrelated, but still content to add somewhere: 
- [ ] `#[inline(always)]`, `#[inline(should)]`, `#[inline(never)]`

**Comment by milancermak** [comment]
* [import aliases](starkware-libs/cairo#2844) `use foo as bar`
* [`EthAddress` type](starkware-libs/cairo#2913) - kinda useful only when creating an L1 bridge, so not sure if it's relevant for the book

**Comment by enitrat** [comment]
We will make an official release for the V1.0.0 of the book - This version will be the reference for developers that want to _deploy_ contracts. 

We will keep working on a version of the book that is continuously deployed with the latest features added to the compiler.  This version will be for developers that want to work with the latest features of the compiler, and don't need to deploy contracts right away.
