### ISSUE TITLE
Confusing documentation under arrays 

### ISSUE THREAD

**Issue by ItayRosenberg** [cairo-book/cairo-book.github.io#107]
It is written:
"Arrays are, in fact, queues whose values can't be popped nor modified."
However, in the next paragraph, it is written: 
"To remove an element from the front of an array, you can use the pop_front()"

**Comment by enitrat** [comment]
We need to be more precise here: along the lines of
> "Arrays are, in fact, queues whose values can't be modified and can only be removed through `pop_front()`."
