### ISSUE TITLE
Strings syntax highlighting

### ISSUE THREAD

**Issue by Itay-Tsabary-Starkware** [cairo-book/cairo-book.github.io#117]
Only the first word in a sentence is highlighted in green.

For example, in the `'not found'.print();` example only the word `not` is highlighted.

https://cairo-book.github.io/ch05-01-enums.html

**Comment by enitrat** [comment]
This is because we're using the rust syntax highlighter for code snippets in markdown files. This is likely not going to be fixed anytime soon
