### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#12]
The introduction should make a succint presentation of what Cairo is for, what you can do with it, and how different it is from other programming languages (immutable memory, etc).
It might make more sense to write the introduction once we have some content written rather than at the beginning.
Estimated time: 2 to 3 hours

**Comment by enitrat** [comment]
@Th0rgal I think you would actually be the most qualified person to write this introduction. What do you think?

**Comment by Th0rgal** [comment]
Would be happy to do it

**Comment by enitrat** [comment]
Great, thanks!

**Comment by Th0rgal** [comment]
wip: https://github.com/Th0rgal/cairo-book.github.io/blob/feat/intro/src/ch00-00-introduction.md

I  tried to focus non what matters for developers. I will add more about the memory model and try to give an intuition of the way the stark process work. What do you think of the part about non determinism, is it too much?

**Comment by enitrat** [comment]
This is great, thank you.

However, I think the following part might be confusing for a new user:

> The most important thing to keep in mind when writing your program is that it will be executed in two different ways. ...

If I were entirely new to Cairo, I think I would be completely lost after reading this. I think rewording it to _"it can be executed"_ would help.

**Comment by Th0rgal** [comment]
Great thanks for the feedback, I will tweak it ;)

**Comment by enitrat** [comment]
Closed by #29
