### ISSUE TITLE
Fix: Address current issues

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#122]
Address the following issues:

#107, #108, #109, #110, #111, #112, #113, #114, #115, #116, #118, #119, #120.

Estimated time: 1 hour

**Comment by enitrat** [comment]
Also address #69

**Comment by 0xEniotna** [comment]
Taking this big boss !

**Comment by 0xEniotna** [comment]
I'm not touching to #118 for the moment. I still need to learn what is a loop 👉👈

**Comment by enitrat** [comment]
you can just remove them now, just verify that it compiles
