### ISSUE TITLE
feat: Derivable traits Appendix

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#134]
This appendix page explains which traits can be derived, how to do it, when it is required, etc.

- Serde
- Copy
- Drop
- PartialEq

You will also research if other traits can be derived as well.

Estimated time: 1 to 2 hours

**Comment by zarboq** [comment]
assign me plz :rocket:

**Comment by enitrat** [comment]
also please include an example of the generated code for each trait !
