### ISSUE TITLE
feat: Starknet plugin Appendix

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#135]
This appendix page will explain what actually happens when the compiler expands the code of a `#[contract]` module to make it a cairo contract.

Namely,
- Storage variables modules (variable storage address, read and write functions generated)
- Events code expansion - serialization of data and `emit_event_syscall` call
- generated contract `__abi` trait
- `__external` module - explain the generated code for external functions (internal function call + serialization)  by using a specific function as example. For now, `view` functions are also expanded under the `__external` module.

Estimated time: 2 hours

**Comment by rkdud007** [comment]
i would love to tackle this one @enitrat XD if there would be reference also could be helpful 🫡

**Comment by enitrat** [comment]
I don't really know if there's a reference for that. You will need to check the compiler code in the Starknet crate, and play around with some contracts and the language server. If you cmd+click on a `var::write` it should take you to the expanded contract file and you can collect snippets from there

**Comment by enitrat** [comment]
Hey @rkdud007 Let's pause this temporarily until V2 comes out :)
