### ISSUE TITLE
feat: Appendix operators and symbols

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#136]
Cairo newcomers have a hard time figuring out which symbols they can use. This appendix will list the symbols available in Cairo, and what they correspond to.

For example, `||` and `&&` (Short-circuiting logical OR/AND) are not available, but `|` and `&` (Bitwise OR / AND) are.

The expected output is similar to the Rust book's [operators appendix](https://doc.rust-lang.org/book/appendix-02-operators.html) page.

Estimated time: 2 to 3 hours (this requires you to dig a bit in the compiler code and test multiple symbols)

**Comment by zarboq** [comment]
I got this :fire: :fire_engine:
