### ISSUE TITLE
feat: keywords

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#137]
This appendix will list the reserved keywords in Cairo, and what they're used for.

For example, the `return` keyword is used to return from a function.
The expected output is similar to the Rust book's [keywords appendix](https://doc.rust-lang.org/book/appendix-01-keywords.html) page.

You can refer to this page of the [cairo documentation](https://github.com/starkware-libs/cairo/blob/main/docs/reference/src/components/cairo/modules/language_constructs/pages/keywords.adoc) Your objective here is to provide context for these keywords and explain what they're used for.

Estimated time: 1 hour

**Comment by rkdud007** [comment]
want to try this one 👋

**Comment by rkdud007** [comment]
yo think you can close this issue :)
