### ISSUE TITLE
feat: Appendix - Cheat sheet of common core library imports

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#141]
I've seen a lot of comments on group chats about compiling errors due to not importing a type or a trait when writing Cairo code.
In this appendix, we'll reference the most common types and traits required to write contracts.
On the top of my head, I can list:
- `OptionTrait`
- `ResultTrait`
- `ContractAddress`
- `ContractAddressZeroable` and `contract_address_const`
- `Into` and `TryInto`
- `get_caller_address`, `get_contract_address`

and probably many others. Let's document it as much as possible so that we don't have to search manually in the compiler source code everytime.

The output must be an appendix page, with one main table with three columns - | Import | Path | Usage |

Estimated time: 1 hour

**Comment by makluganteng** [comment]
can i try to take this ?

**Comment by makluganteng** [comment]
Hi do you guys have like a telegram to ask more specific on how this would be written ?

**Comment by enitrat** [comment]
yes, join us here https://t.me/cairobook

**Comment by makluganteng** [comment]
Okey waiting to be accepted by admin on telegram

**Comment by makluganteng** [comment]
i can say im done but i need help on something.

**Comment by enitrat** [comment]
> i can say im done but i need help on something.

You can open a draft PR and ask your questions in the body

**Comment by enitrat** [comment]
Keeping this open to remind of us updating this section after compiler updates / with new content.

Although, if the LS becomes good enough, we will have auto-import of required traits.
