### ISSUE TITLE
feat: example of named arguments in functions

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#152]
a very small addition that demonstrates how we can use named arguments in functions, e.g.

`fn foo(:address, amount: value, recipient:caller)`

**Comment by venkatnetha** [comment]
Hi, I want to work on this, please assign this to me

**Comment by enitrat** [comment]
great thanks. It's a very small addition that goes in the functions chapter

**Comment by enitrat** [comment]
I'll finish this one
