### ISSUE TITLE
Common Programming concepts

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#17]
In this section, we present how common programming concepts are materialized in Cairo.
We don't go very deep into the language details, and just provide the developer with what's required for a basic program.

Subsections: Variables, Data Types, Functions, Comments, Control Flow

**Comment by Th0rgal** [comment]
I will start working on this. Should I target an audience familiar with programming and explain how to do things or Cairo or should I explain the things?

**Comment by enitrat** [comment]
@Th0rgal the way I see it it's just an introductory page to the section (like an introduction to a chapter) . The real content is in the subsections and most of it is almost done

**Comment by enitrat** [comment]
Closed by #7  #21  #19  #18
