### ISSUE TITLE
Add support for && and || operators.

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#230]
Replace usages of `&` and `|` by `&&` and `||`

Add operators to [Appendix 2](https://cairo-book.github.io/appendix-02-operators-and-symbols.html)

Estimated time: 30mins

**Comment by enitrat** [comment]
@0x471 can you finish this over the weekend?

**Comment by 0x471** [comment]
> @0x471 can you finish this over the weekend? otherwise I'll take it, it's just one line to add to the appendix

I apologize, but I'm unable to complete it due to my schedule

**Comment by enitrat** [comment]
sure, no problem!
