### ISSUE TITLE
simplify the `impl` mechanism with #[generate_trait]

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#233]
We can now use the `#[generate_trait]` attribute on an implementation to directly generate the trait corresponding to an implementation.
In this issue, you will demonstrate how to use it, with examples. You will cover generic and non-generic traits.
```rust
  #[generate_trait]
  impl AddMethods for AddMethodsTrait {
      fn method(self: TypeWithNewMethods) -> u32 { ... }
  }
  ```
  
  Estimated time: 30mins

**Comment by ametel01** [comment]
Happy to take this if possible
