### ISSUE TITLE
refactor: Update contract syntax 

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#234]
We can refactor the whole `Starknet` section with the new contract syntax. Here is the rationale behind the syntax change.
https://community.starknet.io/t/cairo-1-contract-syntax-is-evolving/94794?u=feedthefed
We need to provide an extensive description of the new contract syntax mechanism, along with examples.
If you want to take this issue, you will provide a complete refactoring of the Starknet contract section, improving the description of how to build contracts, making sure that each step is documented in the best way possible.
You can reuse the explanation provided in the community forum post.
The coverage of the syntax update v2 (components) is not in the scope of this issue.
Estimated time: 2 to 3 hours

**Comment by enehizy** [comment]
the time to complete is 2 - 3 hours?

**Comment by enitrat** [comment]
Assuming that you already know how everything works and that you can explain it properly, yes.
@ametel01 has already worked on updating the syntax in Cairo files, but in-depth explanations are still required
