### ISSUE TITLE
feat: extend `#[generate_trait]` part

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#263]
reference: https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-plugins/src/test_data/generate_trait

est. 2 to 3 hours

**Comment by rkdud007** [comment]
@enitrat i can do this :)

**Comment by enitrat** [comment]
@rkdud007 Cool! Please take your time, explain things clearly and provide comprehensive and meaningful examples 😄 
There is a very limited part about `generate_trait` right now, we want to show what happens under the hood, what code is being generated, how to use it for generics, etc.

**Comment by rkdud007** [comment]
can I know where is generate_trait currently written? I cannot find it 

I'm planning to add it on 7.2 traits in cairo bottom

**Comment by rkdud007** [comment]
actually I suggest to make another chapter or appendix for Plugins.

**Comment by enitrat** [comment]
https://github.com/cairo-book/cairo-book.github.io/blob/cairo-2.0/src/ch07-02-traits-in-cairo.md#implementing-a-trait-without-writing-its-declaration

**Comment by rkdud007** [comment]
oh wait its on cairo2.0 branch, so that means i better push it on cairo2.0 branch right?

**Comment by enitrat** [comment]
yes
