### ISSUE TITLE
feat: macros

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#264]
Create a section under "Advanced Features" that explains how to use available macros`consteval_int!`, `array!`, and how they work under the hood.

references: https://github.com/starkware-libs/cairo/commit/35953ba63e05c42c547960749a78255f4832cffe
https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-plugins/src/plugins/inline_macros
https://doc.rust-lang.org/book/ch19-06-macros.html

est. 1 hour

**Comment by 0xEniotna** [comment]
Can I take this one ser ? 👉👈
