### ISSUE TITLE
feat: L1 <> L2 messages

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#283]
A chapter focused on how to send messages to L1 and receive messages from L1.

An important fact that must be written in the book: If the payload sent from L1 contains values higher than the max amount in a felt, the message will never be consumed on L2. On L1 side, we must ensure that values never go above MAX(felt252)

**Comment by 0xEniotna** [comment]
will do asap ser

**Comment by enitrat** [comment]
that's some quality nerdsnipe 🔫
