### ISSUE TITLE
bug: Missing example

### ISSUE THREAD

**Issue by stoobie** [cairo-book/cairo-book.github.io#287]
In https://book.cairo-lang.org/ch05-02-the-match-control-flow-construct.html

It says: 

> For example, the following code prints “Lucky penny!” every time the method is called with a Coin::Penny(()), but still returns the last value of the block, 1:

Then there is a blank line where there should be an example, but it's just a blank code line:

![image](https://github.com/cairo-book/cairo-book.github.io/assets/39279277/e46b164b-6b66-436e-8729-b159d7806d7a)

**Comment by enitrat** [comment]
Thanks, fixed!
