### ISSUE TITLE
feat: pre-component extensibility

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#312]
https://community.starknet.io/t/cairo-1-contract-syntax-is-evolving/94794/35

**Comment by julio4** [comment]
Should we already document this as it's not available right now?

**Comment by enitrat** [comment]
Hey @julio4, actually this will become irrelevant when components are merged. This is just a way to produce composability of contracts before the component system is released. Basically what happens is that you can access the state of the other contract, as if it was part of the state of your current contract, and modify it. I'm not sure when the component system will be released

**Comment by julio4** [comment]
I see, I thought you already wanted to document the new component syntax, hence my question!

**Comment by enitrat** [comment]
If you wanna pick this one up, feel free to, you will need to explore a bit how it works, it should take you maybe 2 hours in total. You can check how it's done in [Pragma's repository](https://github.com/Astraly-Labs/pragma-oracle/blob/d6ca74de66622cf3166cfec074934223c3afc3bb/src/publisher_registry/publisher_registry.cairo#L50)
