### ISSUE TITLE
`--single-file` flag for `cairo-run`

### ISSUE THREAD

**Issue by lancenonce** [cairo-book/cairo-book.github.io#313]
When following the instructions in section 1.2 of the book, the command `$ cairo-run main.cairo` did not work on my x86 mac machine. I ran the command using zsh. When running it, I got this error:
```bash
Error: The given path is a file, but --single-file was not supplied.
```
After supplying the `--single-file` flag, the run succeeded.

I think the book should be updated to include the `--single-file` flag for the hello-world setup.

**Comment by enitrat** [comment]
Hi @lancenonce ,this is because you're using a compiler version that is newer than the one the book is written for (2.0.0). See #290
