### ISSUE TITLE
Chapter 7.1: change "lib.cairo root module by default is empty".

### ISSUE THREAD

**Issue by OkoliEvans** [cairo-book/cairo-book.github.io#319]
"lib.cairo is the default root module of the crate, which is also the main entry point of the package. By default, it is empty." is what is currently published, but this is not true, as lib.cairo is not empry by default, but contains some sample dummy codes.

"fn fib(a: felt252, b: felt252, n: felt252) -> felt252 {
    match n {
        0 => a,
        _ => fib(b, a + b, n - 1),
    }
}
". 

So the content should be edited to effect this.

**Comment by enitrat** [comment]
It is empty by default - this is just a code snippet that is generated by Scarb purely as an example (and is not the default behavior), but if you remove it you're still able to compile the crate.

**Comment by OkoliEvans** [comment]
Okay. I just thought the statement might be a bit contradictory to new users when they compare what they read with what they actually see on code editor.

**Comment by enitrat** [comment]
I removed this line to not confuse the reader, thanks @OkoliEvans

**Comment by OkoliEvans** [comment]
> 

Awesome, that's cool. If I see any part that needs editing I will still open another issue. :+1:
