### ISSUE TITLE
Cairo's Ownership system

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#34]
Cairo has an ownership system that is used for its linear type system, ensuring that **all values are used exactly once**.
This ensures that:
 - **Dictionaries** are squashed before the end of a program, ensuring the soundness of Cairo programs
 - **Array indices** can't be written twice.
 
 The chapter will introduce the Cairo ownership system and why it's required for the safety of the language (a good part is covered  [here ](https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-7f32808421f5))
 It will give various examples of what can / cannot be copied, can / cannot be dropped, introduce destructors and how to use them.
 This part doesn't introduce `ref` and `@ snapshots` yet
 
 Estimated time: 3 to 4 hours
 
 reference: [sw-repo doc](https://github.com/starkware-libs/cairo/blob/103c46951e58f30d6f78a396a2e3abf4d76527d8/docs/reference/src/cairo/modules/ROOT/pages/linear-types.adoc#L4)

**Comment by shramee** [comment]
Happy to take this.
