### ISSUE TITLE
Enrich ''Storage Variables'' chapter

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book.github.io#367]
Hi @enitrat  , 
after completing the Starknet Storage Layout quest yesterday on NG, i spent a few hours facing a problem due to a misunderstood concept.  

from cairo book : 

In mappings, the address of the value at key k_1,...,k_n is h(...h(h(sn_keccak(variable_name),k_1),k_2),...,k_n) where ℎ is the Pedersen hash and the final value is taken mod2251−256. You can learn more about the contract storage layout in the [Starknet Documentation](https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/contract-storage/#storage_variables)

I think this section should be enriched : when reading it, it feels like the nested pederson scheme should only be applied to nested mappings, with 2 different keys to use in the pedesen hash function.

But if you have a single mapping, with a u256 as a key, you should also apply 2 nested pedersen hash, with the only key of the mapping (actually 2 felt252, but with max size U128) considered as 2 separate keys. so basically, a single mapping with a u256 as a key is identical to a 2 nested mappings?

I think i could try to rewrite this section to make it clearer, and maybe add more content about structs storage, and more important about how u256 are stored underneath the hood.

Just let me know if you think this is relevant, but i think it is as i didn't fully understand all this concept when reading cairo book and starknet documentation.

i've been  partially helped with this blog post, but it's all about cairo 0, maybe some fresh content about u256 in cairo book would be great.

https://dev.to/peterblockman/cairo-uint256-ojf

**Comment by enitrat** [comment]
> so basically, a single mapping with a u256 as a key is identical to a 2 nested mappings?

Not only restricted to u256 but I think that's how it would work for all structs? Since a struct is not something that can be the input of a hash function, but it's serialized members are.

Anyway, if you want to take this work, I'll be happy to support it! I really appreciate external initiatives :)

**Comment by TAdev0** [comment]
yes, it seems logic this would work this way for all structs.
I think i went wrong because of starknet documentation : 

"If it is a (nested) mapping, then the address of the value at key k_1,...,k_n is h(...h(h(sn_keccak(variable_name),k_1),k_2),...,k_n)  mod2^251−256."

The "nested" word made me understand it as : 
- if you have a single mapping -> h(sn_keccak(variable_name),k_1)
- if you a mapping into a mapping -> h(h(sn_keccak(variable_name),k_1),k_2)

probably because i spent multiple months on solidity and i know a struct or array cannot be a key for a mapping with the EVM.

But it actually meant : if the key of your single mapping is more than a single felt252, then use all these ''felt 252 sub-keys'' with nested pedersen hash to obtain the address. Am i right?
If yes, what about mappings into mappings? does it work the same way? and it it possible to have an array as a key with cairo, and serialize all values to pass it to pedersen function?

What i though i could add :

- 2.2. Data types : add a section into ''Integer types'' , or a separate one, to talk about uint256 specifically, as i doesn't fit into a felt252. explain how it works  under the hood (struct of 2 felt252 that contains 2 * 128 bits of interest, with left padding for each felt).  Btw, maybe the chapter ''Data types'' could be renamed ''Basic Data Types'', as it doesn't include custom data types such as structs?

- 12.3.1 Storage Variables : 
                                              -  add a section '' Storing basic data types '' which explains how and where types that fit into a felt252 are stored (first 250 bits of sn_keccak("variable name"). We could also add a specific sub-section for u256,  which takes 2 contiguous slots with a specific format (low, high).  (btw, i saw once a u512, is it a specific custom type or is it available in core library? If it is in core library, maybe we could add it in the array in 2.2 Data types.
                                               - In Storing customs struct, just add a few lines to precise that it works like basic data types for the location (first 250 bits of sn_keccak("variable name"), and then elements are stored contiguously .
                                               
Tell me what you think of these potential updates :)

**Comment by enitrat** [comment]
> 2.2. Data types : add a section into ''Integer types''

There is already a section "Integer type", but it doesn't talk about the inner construction of `u256`. Feel free to add you changes there

> (btw, i saw once a u512, is it a specific custom type or is it available in core library? If it is in core library, maybe we could add it in the array in 2.2 Data types.

u512 is a type defined in the corelibrary that is used for `u256_wide_mul`. As it doesn't implement common traits required to perform operations with it, it has been excluded from the book on purpose. Moreover, the requirement for a `u512` type is extremely rare 


> add a section '' Storing basic data types '' which explains how and where types that fit into a felt252 are stored (first 250 bits of sn_keccak("variable name").

Sounds good. This is basically every non-struct type

> We could also add a specific sub-section for u256, which takes 2 contiguous slots with a specific format (low, high)

I don't really agree, u256 should be treated like any other struct, I would rather rename [Storing Custom Structs](https://book.cairo-lang.org/ch99-01-03-01-storage-variables.html#storing-custom-structs) to Storing structs, and add details about the address calculation here
Perhaps it would be best to have

# Storage Variables 

## Storing Structs

## Storing Mappings 

## Reading from Storage

## Writing to Storage
