### ISSUE TITLE
Possible error in Bringing Paths into Scope with the use Keyword section 

### ISSUE THREAD

**Issue by TAdev0** [cairo-book/cairo-book.github.io#368]
@enitrat 

just noticed there's an issue with the first snippet of Bringing Paths into Scope with the use Keyword section  :

```
mod front_of_house {
    mod hosting {
        fn add_to_waitlist() {}
    }
}

use restaurant::front_of_house::hosting;

fn eat_at_restaurant() {
    hosting::add_to_waitlist(); // ✅ Shorter path
}

```

should probably be : 

```
mod front_of_house {
    mod hosting {
        fn add_to_waitlist() {}
    }
}

use front_of_house::hosting;

fn eat_at_restaurant() {
    hosting::add_to_waitlist(); // ✅ Shorter path
}

```

there is this ''restaurant'' word coming from nowhere, the cairo book snippet doesn't compile and my suggestion does, so i guess there is a little mistake?

**Comment by enitrat** [comment]
`restaurant` is the name of the crate which should be given prior to this snippet

> We have a crate named restaurant in which we have a module named front_of_house that contains a module named hosting

**Comment by enitrat** [comment]
You can add it as a code comment inside the snippet so that even people skim-reading can understand what's going on

**Comment by TAdev0** [comment]
Oh yeah my bad .. I understand. Didn't read the whole Managing Cairo Project in a raw.. my fault. As the crate name wasn't explicitly recalled in this sub section, I went wrong. Sorry for that

**Comment by enitrat** [comment]
@TAdev0 you can still add the comment in the snippet if you want

**Comment by TAdev0** [comment]
@enitrat  PR done!
