### ISSUE TITLE
Testing Cairo programs

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#38]
This will chapter cover testing **pure Cairo** programs. 
- Test modules ( `mod tests {...}` ) should be annotated with the `#[cfg(tests)]` attribute to reduce the size of the compiled code
- How to check values with the `assert` function
- How to expect failure from a test (with/without an expected error message)
- Differentiating unit tests and integration tests

Note: Unlike Rust, unit tests should not be with the source code.
Estimated time: 4 hours

**Comment by irisdv** [comment]
Can work on this issue
