### ISSUE TITLE
Add information about the prelude

### ISSUE THREAD

**Issue by glihm** [cairo-book/cairo-book.github.io#380]
In basecamp we've seen that it can be useful to have a short paragraph and information about the prelude and what's is inside.

The work may be to summarize what's here:

https://github.com/starkware-libs/cairo/blob/v2.2.0/corelib/src/starknet.cairo
https://github.com/starkware-libs/cairo/blob/v2.2.0/corelib/src/lib.cairo

**Comment by enitrat** [comment]
Great idea! That's new from 2.2.0 afaik. Wanna take this @glihm or should I propose to someone else?

**Comment by glihm** [comment]
@enitrat yep I can make a proposal for this one. 🫡 except if you think that it can be a good first issue.

**Comment by enitrat** [comment]
@glihm its a good first issue indeed, maybe start with the messaging changes you mentioned to me 🤠

**Comment by axelizsak** [comment]
Yo, can I take this one ?

**Comment by enitrat** [comment]
@axelizsak go ahead

**Comment by axelizsak** [comment]
Perfect, I'll do it all this weekend
