### ISSUE TITLE
Fixing 1.2, Hello World

### ISSUE THREAD

**Issue by yozhiik** [cairo-book/cairo-book.github.io#383]
Slightly off-puttingly, the hello world doesn't work! I think it's maybe from an earlier era before the upgrade where gas was mandatory, but when I do scarb cairo-run, I get "program requires gas counter, please provide `--available-gas` argument"

**Comment by yozhiik** [comment]
this wasn't working because I'd added 
``[dependencies]
starknet = ">=2.2.0"

[[target.starknet-contract]]``

to the Scarb.toml file, I'd assumed that was the next step but it created errors.

**Comment by enitrat** [comment]
Hey @yozhiik thanks for reporting this - what you added to the Scarb.toml file is not supposed to fix this bug you had.

Can you confirm with me the following (see discord):

```
❯ scarb --version
scarb 0.7.0 (58cc88efb 2023-08-23)
cairo: 2.2.0 (https://crates.io/crates/cairo-lang-compiler/2.2.0)
sierra: 1.3.0
``` (or higher)

File structure:
```
.
├── Scarb.toml
├── src
│   ├── hello_world.cairo
│   └── lib.cairo
```

`lib.cairo` content
```
mod hello_world;
```

`hello_world.cairo` content:
```
use debug::PrintTrait;
fn main() {
    'Hello, World!'.print();
}
```
