### ISSUE TITLE
Implementing your own data structure using Dicts

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#386]
References (add a link to them, and use them as code examples): 
- https://github.com/keep-starknet-strange/alexandria/blob/main/src/data_structures/src/vec.cairo
- https://github.com/keep-starknet-strange/alexandria/blob/main/src/data_structures/src/stack.cairo
- https://github.com/keep-starknet-strange/alexandria/blob/main/src/data_structures/src/queue.cairo

Goes into 3. Common Collections - Chapter 3.3

Explain how mutable data structures can be simulated using dicts

**Comment by chachaleo** [comment]
Can I take it ?
