### ISSUE TITLE
Chapter 12.5.1 Account Descriptor creation guide confusing

### ISSUE THREAD

**Issue by OkoliEvans** [cairo-book/cairo-book.github.io#388]
The account descriptor creation guide in the Deployment and Interacting with a Voting contract chapter is confusing and not straightforward. In the text, 'touch ~/.starkli-wallets/deployer/account0_account.json' will only create an empty file, but the user is supposed to copy the sample Descriptor on the page, then paste in the created file and fill with real values. But the guide did not explain this, which makes it difficult for users to work through this easily. @enitrat You will edit it or I should open PR?

**Comment by enitrat** [comment]
Hi, please make the required changes! You can get some help from the Starkli Book instructions here https://book.starkli.rs/tutorials/starkli-101

**Comment by OkoliEvans** [comment]
> Hi, please make the required changes! You can get some help from the Starkli Book instructions here https://book.starkli.rs/tutorials/starkli-101

I have made the changes and opened a PR @enitrat
