### ISSUE TITLE
error: Identifier not found.

### ISSUE THREAD

**Issue by kenkomu** [cairo-book/cairo-book.github.io#403]
I am trying to run this code using: cairo-run dict.cairo -s
Here is the code.

struct Entry<T> {
    key: felt252,
    previous_value: T,
    new_value: T,
}
use dict::Felt252DictEntryTrait;

fn custom_get<T, impl TDefault: Felt252DictValue<T>, impl TDrop: Drop<T>, impl TCopy: Copy<T>>(
    ref dict: Felt252Dict<T>, key: felt252
) -> T {
    // Get the new entry and the previous value held at `key`
    let (entry, prev_value) = dict.entry(key);

    // Store the value to return
    let return_value = prev_value;

    // Update the entry with `prev_value` and get back ownership of the dictionary
    dict = entry.finalize(prev_value);

    // Return the read value
    return_value
}

**Comment by enitrat** [comment]
The following code doesn't match the one presented in the book. It doesn't compile because it is not correct.
