### ISSUE TITLE
Request to Add New Smart Contract Example  

### ISSUE THREAD

**Issue by hardiktheprogrammer** [cairo-book/cairo-book.github.io#407]
I would  like to add a New  example  Smart contract at another example page  , can you please assign me 
 https://book.cairo-lang.org/ch99-01-04-00-other-examples.html

**Comment by enitrat** [comment]
What contract do you want to add? What value does it bring? I don't think we need more examples yet.

**Comment by hardiktheprogrammer** [comment]
Yeah I want to add  ICO tokens and vesting Smart Contract Development it helps to understand the in-depth Development Concept

**Comment by enitrat** [comment]
Hey, that's a good idea! However, I think it would be more suitable for https://starknet-by-example.voyager.online/, a collection of advanced patterns, applications and examples regarding Starknet SC development. 

However, I would accept a thorough example of a contract that uses the component mechanism, similar to how the Voting contract chapter is written. I would rather not collect too many examples here.

**Comment by Nonnyjoe** [comment]
@enitrat How about a piggy bank contract designed using a factory contract model and uses component mechanism for ownership / access control. Would it be a good addition?
