### ISSUE TITLE
How to use eth to pay? Is there any sample code?

### ISSUE THREAD

**Issue by my-Gem** [cairo-book/cairo-book.github.io#415]

**Comment by enitrat** [comment]
Eth is an erc20, so you can just call the `transfer` function to transfer ETH to a recipient (or approve + transferFrom if the you want to to transfer ETH from another account)

**Comment by enitrat** [comment]
You can ask to create an example of ETH / ERC20 transfer in this repo https://github.com/NethermindEth/StarknetByExample/
