### ISSUE TITLE
Unit tests: Discuss where they should be located

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#56]
This issue is a discussion related to #38 https://cairo-book.github.io/ch09-02-test-organization.html#unit-tests

I'm not sure exactly how we should present it. If we're writing pure Cairo programs it doesn't really matter but most people will be using Cairo for Starknet contracts. Even if you're writing unit tests in a library, including tests in the library directory means that the tests will be shown on block explorer when verifying contracts that depend on this library, which is not great.

**Comment by hurrikaanig** [comment]
Wouldn't adding unit tests in contract increase deployment gas also ?

**Comment by enitrat** [comment]
No they're ignored during compilation when marked with #[cfg(test)]
