### ISSUE TITLE
Common Collections: Arrays (& Spans)

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#62]
I think we should move the `Array` from Data Types to a `Common Collection` section, along with Dictionaries.

Estimated time: 1 hour (move & improve existing section, introduce Spans and where they're used)

**Comment by Matth26** [comment]
Can I propose something for this one?

**Comment by enitrat** [comment]
> Can I propose something for this one?

Yes, go ahead, but make sure it is as good as the rest of the book!
