### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by milancermak** [cairo-book/cairo-book.github.io#69]
Hey,

since I can't get access to the TG group and I'm too lazy to fix the issues myself, I'm writing here a couple of disjoint points I found so far while glossing over the book.

1) In [felt type](https://cairo-book.github.io/ch02-02-data-types.html#felt-type), I find the latex notation used to define P quite strange.
2) In [boolean type](https://cairo-book.github.io/ch02-02-data-types.html#the-boolean-type): "Booleans are one byte in size." IMO that statement is not true. Did you want to say one *bit*? But then it's felts all the way down, so not sure if that's 100% correct either.
3) In [short string](https://cairo-book.github.io/ch02-02-data-types.html#the-short-string-type), you should mention that the max length of a short string is 31 chars and also the reason why. It's valuable to know.
4) A lot of the code snippets are formatted in a weird way. Consider running cairo-format (which is, coincidentally, mentioned in the appendix) on all of them, so people get a habit of creating properly formatted code.

In any case, great work overall, you absolute chads!

**Comment by fricoben** [comment]
Thanks a lot for the feedbacks 🔥
