### ISSUE TITLE
Explain every steps more in details 

### ISSUE THREAD

**Issue by quentin-abei** [cairo-book/cairo-book.github.io#74]
This book is supposed to be beginner friendly yet it lacks details.
Like how to install scarb on any machine ? You just Saïd download the archive and unzip it ... This Can work if i use windows OS or Mac OS, but i use linux inside windows.
I tried looking for a link to curl or wget the scarb archive but it just donwload the zipped file to my windows machine . I tried asking on twitter, got ignored. Iam stuck at scarb installation on WSL for 2 days already... This is what you call beginner friendly ?

**Comment by fricoben** [comment]
Ask chatgpt about it

**Comment by enitrat** [comment]
`curl -L https://github.com/software-mansion/scarb/releases/download/v0.2.0-alpha.0/scarb-v0.2.0-alpha.0-aarch64-apple-darwin.tar.gz | tar -xz`

replace the URL with the correct version
