### ISSUE TITLE
cairo-run command suddenly output "argument not found"

### ISSUE THREAD

**Issue by quentin-abei** [cairo-book/cairo-book.github.io#75]
Afetr insatlling scarb and writing my first hello_scarb cairo-run command just do not recognize the file argument i pass , i tried starting a new project and it is the same 
full output ```usage: cairo-run [-h] [-v] [--program PROGRAM] [--program_input PROGRAM_INPUT] [--steps STEPS]
                 [--min_steps MIN_STEPS] [--debug_error] [--no_end] [--print_memory] [--relocate_prints]
                 [--secure_run] [--no_secure_run] [--print_info] [--print_segments] [--print_output]
                 [--memory_file MEMORY_FILE] [--trace_file TRACE_FILE]
                 [--run_from_cairo_pie RUN_FROM_CAIRO_PIE] [--cairo_pie_output CAIRO_PIE_OUTPUT]
                 [--debug_info_file DEBUG_INFO_FILE] [--air_public_input AIR_PUBLIC_INPUT]
                 [--air_private_input AIR_PRIVATE_INPUT]
                 [--layout {plain,small,dex,recursive,starknet,recursive_large_output,all_solidity,starknet_with_keccak,dynamic}]
                 [--tracer] [--profile_output PROFILE_OUTPUT] [--proof_mode] [--show_trace]
                 [--flavor {Debug,Release,RelWithDebInfo}] [--python_dependencies PYTHON_DEPENDENCIES]
cairo-run: error: unrecognized arguments: src/lib.cairo```

**Comment by enitrat** [comment]
you're trying to run the Cairo 0 CLI
