### ISSUE TITLE
Recoverable Errors with `Result<T,E>`

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#79]
- Explain how you can handle an execution error by introducing the `Result` enum
- Give an example with existing core library operations (handling e.g. overflowing addition)
- Shortcuts to panic on error: `expect`, `unwrap` methods defined on the `ResultTrait` trait
- Error propagation (see [rustbook](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#propagating-errors))
- The `?` operator

As this concept shares a lot of similarities with Rust, the submitted PR will follow the content of the Rust book, adapting all examples to Cairo, and removing concepts that don't have an equivalent. The examples will need to make sense in the context in the execution of a Cairo program.

Estimated time: 2-3 hours

**Comment by 0xEniotna** [comment]
Can I try something for that one big boss ?
