### ISSUE TITLE
Section on Cairo setup

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#8]
A section setting up cairo.
Inside the section we need:
- Manual steps, following the  [cairo template](https://github.com/auditless/cairo-template)  instructions (adapted to match the shell script)
- Installation script https://github.com/franalgaba/cairo-installer
Estimated time: 1 hour.

**Comment by fricoben** [comment]
@Th0rgal eZ to do for you using GPT

**Comment by hurrikaanig** [comment]
Is @Th0rgal taking care of this ? If not I can

**Comment by enitrat** [comment]
Go ahead @hurrikaanig
