### ISSUE TITLE
Starknet contracts: ABIs and cross-contract interactions

### ISSUE THREAD

**Issue by enitrat** [cairo-book/cairo-book.github.io#83]
This section will cover more advanced concepts around smart contracts:

- Declaring contract interfaces with `#[abi]`, and what happens under the hood
- Regular contract calls using the dispatcher pattern (if relevant, introduce how the [dispatcher plugin](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-starknet/src/plugin/dispatcher.rs) works )
- Library calls

This section will follow the same standard as the rest of the book, making sure that all concepts are explained properly to someone new to Starknet/Cairo, and will include an example of interactions between contracts/libraries

@milancermak would you be interested in taking this? I think it would be great since you wrote this [cairopractice blog post](https://cairopractice.com/posts/calling-contracts-using-dispatch/)

Estimated time: 3 hours

**Comment by Darlington02** [comment]
taking this
