### ISSUE TITLE
Protostar

### ISSUE THREAD

**Issue by piwonskp** [cairo-book/cairo-book.github.io#86]
Hey,

I've recently started using [Protostar](https://github.com/software-mansion/protostar) and it's got a great support for cairo 1. Perhaps it would be a good idea to add a chapter on the tool?

**Comment by enitrat** [comment]
Yes! This will be next after the Starknet contract sections are covered.

**Comment by piwonskp** [comment]
I can help with that if it's needed :)

**Comment by enitrat** [comment]
I think it's best if we start after the release next Sunday. I don't think it fits well in Cairo projects yet, I would like to wait for the Scarb integration. Then, sure!
